---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Ensure dependencies are installed
      package:
        name: cronie
        state: present

  roles:
    - role: davidalger.holland
